# Web Configuration
browser=chrome
web.url=https://www.saucedemo.com/
web.username=standard_user
web.password=secret_sauce
headless=true
maximize=true
web.invaliduser=xyz
web.invalidpass=xyz

# Mobile Configuration
platform=android
device.name=Pixel_8
platform.name=Android
automation.name=UiAutomator2
appium.server.url=http://127.0.0.1:4723
app.path=src/test/resources/apps/ApiDemos-debug.apk
explicit.wait=10
mobile.execution=browserstack

browserstack.username=
browserstack.access.key=
browserstack.url=https://hub-cloud.browserstack.com/wd/hub
browserstack.app=bs://234774b745de75493c922554c35f2136ecc11f5a
browserstack.device=Samsung Galaxy S22
browserstack.os.version=12.0
browserstack.project=WebAndAndroidAutomation
browserstack.build=Local Mobile Build